# Generated by Django 6.0.1 on 2026-04-23 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.IntegerField(unique=True)),
                ('bus_name', models.CharField(max_length=100)),
                ('kv', models.FloatField()),
                ('zone', models.CharField(choices=[('Zone-N', 'Zone North'), ('Zone-S', 'Zone South')], default='Zone-N', max_length=20)),
                ('bus_type', models.CharField(choices=[('Smart', 'Smart Meter'), ('Legacy', 'Legacy Meter')], default='Smart', max_length=20)),
            ],
            options={
                'verbose_name': 'Network Bus',
                'verbose_name_plural': 'Network Buses',
                'ordering': ['bus_id'],
            },
        ),
        migrations.CreateModel(
            name='SmartMeterLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('p_kw', models.FloatField()),
                ('q_kvar', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='network.networkbus', to_field='bus_id')),
            ],
            options={
                'verbose_name': 'Smart Meter Load',
                'ordering': ['timestamp', 'bus'],
                'unique_together': {('bus', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='VoltageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('vm_pu', models.FloatField()),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voltage_results', to='network.networkbus', to_field='bus_id')),
            ],
            options={
                'verbose_name': 'Voltage Result',
                'ordering': ['timestamp', 'bus'],
                'unique_together': {('bus', 'timestamp')},
            },
        ),
    ]
